--프로그래머스,join
--없어진 기록 찾기
SELECT ANIMAL_ID,NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
ORDER BY ANIMAL_ID;

--있었는데요 없었습니다
SELECT OUTDATE.ANIMAL_ID, OUTDATE.NAME--,OUTDATE.DATETIME,INDATE.DATETIME
FROM ANIMAL_OUTS OUTDATE INNER JOIN ANIMAL_INS INDATE
 ON OUTDATE.ANIMAL_ID = INDATE.ANIMAL_ID
WHERE OUTDATE.DATETIME < INDATE.DATETIME
ORDER BY INDATE.DATETIME